### PR TITLE
🐛(languages) fix currentLanguage in profile menu

### LINKED ISSUE #1091: Wrong language detected in profile
## Wrong language detected in profile

**Problematic behavior**
L'interface s'affiche en français mais le sélecteur de langue dans le profil indique "EN". Forcer le français ne fait rien ; forcer l'anglais bascule toute l'interface.

**Expected behavior**
La langue détectée dans le profil devrait correspondre à la langue de l'interface.

**Steps to Reproduce**
1. Se connecter (interface en français)
2. Cliquer sur la photo de profil
3. Consulter la langue sélectionnée → affiche "EN"
4. Forcer "Français" → rien ne se passe
5. Forcer "Anglais" → toute l'interface passe en anglais

*Ref: #1074*

### PR DESCRIPTION
**Pull request by elvoisin**
Fix currentLanguage in profile menu

### CODE REVIEW

File: src/frontend/apps/desk/src/features/language/LanguagePicker.tsx [hunk 1]
```diff
@@ -10,11 +10,13 @@ export const LanguagePicker = () => {
   const { i18n } = useTranslation();
   const { preload: languages } = i18n.options;
   Settings.defaultLocale = i18n.language;
```
Comment (qbey) [inline src/frontend/apps/desk/src/features/language/LanguagePicker.tsx:12]: Is `Settings.defaultLocale` still useful?

**Review by qbey — APPROVED** [review]
