### PR TITLE
🚸(mailboxes) improve error message when no secondary email

### LINKED ISSUE #1080: Unclear message when unable to reset password because mailbox secondary email is not set
## Bug Report

**Problematic behavior**
When admin (or mailbox owner) try to reset a password without having set a secondary email, they get a vague error
Image

**Expected behavior/code**
We could improve the message to make it clear to user that they've got to set the secondary email before attempting to reset password.

**Steps to Reproduce**
1. admin on a domain
2. tries to reset the password on a mailbox whom secondary email == None
3. And then the bug happens!

**Environment**
- People version: v1.23.1

### PR DESCRIPTION
**Pull request by mjeammet**
## Purpose

improve error message when trying to reset password on a mailbox not having a secondary email.
Fixes #1080

### CODE REVIEW

File: src/frontend/apps/desk/src/features/mail-domains/mailboxes/components/panel/PanelActions.tsx [hunk 1]
```diff
@@ -61,7 +61,11 @@ export const PanelActions = ({ mailDomain, mailbox }: PanelActionsProps) => {
       {
         onSuccess: () =>
           toast(t('Successfully reset password.'), VariantType.SUCCESS),
-        onError: () => toast(t('Failed to reset password'), VariantType.ERROR),
+        onError: (error) =>
+          toast(
+            error.cause?.[0] || t('Failed to reset password'),
```
Comment (qbey) [inline src/frontend/apps/desk/src/features/mail-domains/mailboxes/components/panel/PanelActions.tsx]: This will display a message in English, even for French users... Either translate the message in the backend, or enforce error detection and message in frontend.
